apiVersion: v1
kind: Pod
metadata:
  name: 'httpd'
  labels:
    function: 'httpd'
spec:
  containers:
  - name: 'httpd'
    image: docker.io/ovidiufeodorov/httpd:latest
    #imagePullPolicy: Never
    env:
    #  - name: HTTPD_PORT
    #    value: "22222"
    # This inhibits automatic index.html update
      - name: NO_INDEX_UPDATE
        value: "true"
    volumeMounts:
      - name: local-root
        mountPath: /usr/local/apache2/htdocs
  volumes:
    - name: local-root
      hostPath:
        path: /Users/ovidiufeodorov/tmp/httpd
---
apiVersion: v1
kind: Service
metadata:
  name: 'httpd'
spec:
  type: 'LoadBalancer'
  selector:
    function: 'httpd'
  ports:
    - name: 'http'
      protocol: 'TCP'
      port: 80
      targetPort: 80
