
originator: KinesisProducer

server:
  port: 64398

management:
  port: 8082
  context-path: /manage

#security:
#  user:
#    name: admin
#    password: 2c76788d-e661-49fd-baba-4b41e7c1dd47

spring.cloud.stream:
  bindings:
    channel-from-kinesis:
      destination: ovidiu-test
      content-type: application/json
      consumer:
        headerMode: none

cloud:
  aws:
    region:
      static: us-west-2


logging:
  level:
    com:
      amazonaws: INFO
    org:
      apache:
        http: INFO